### ISSUE TITLE
Tests crash running under Node.js 20.9.0 on Ubuntu 20.04/WSL2

### ISSUE THREAD

**Issue by lloydk** [LeaVerou/color.js#343]
I'm trying to run the tests but they're failing with the following error:
```
~/test/color.js:[main]$ npm run test

> colorjs.io@0.4.5 test
> node tests/index.js

node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^

TypeError: Cannot read properties of undefined (reading 'pass')
    at TestResult.getSummary (file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:234:13)
    at TestResult.toString (file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:261:18)
    at file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:271:45
    at Array.flatMap (<anonymous>)
    at TestResult.toString (file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:271:30)
    at file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:271:45
    at Array.flatMap (<anonymous>)
    at TestResult.toString (file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:271:30)
    at file:///home/lloydk/test/color.js/node_modules/htest.dev/src/js/classes/TestResult.js:271:45
    at Array.flatMap (<anonymous>)

Node.js v20.9.0
```

This is with a fresh checkout of color.js running under Ubuntu 20.04 on WSL2.

**Comment by LeaVerou** [comment]
Thanks! We're actively working on both ends of this rn so here be dragons. Should be fixed now!

**Comment by lloydk** [comment]
Yeah, not doing anything with the new color spaces until things are more stable.

Also getting this error now.

```
~/test/color.js:[main]$ npm run test

> colorjs.io@0.4.5 test
> cd tests && htest

sh: 1: htest: not found
```

**Comment by lloydk** [comment]
```
> npx htest ./tests

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /home/lloydk/.npm/_logs/2023-11-13T22_18_37_667Z-debug-0.log
```

I think the issue is in the package.json for htest.dev

```
  "bin": {
    "htest": "./src/cli.js"
  },
```

should be

```
  "bin": {
    "htest": "./src/js/cli.js"
  },
```

**Comment by lloydk** [comment]
I think `src/js/cli.js` in htest.dev needs to be executable as well.

**Comment by lloydk** [comment]
After those issues are resolved:
```
~/test/color.js:[main]$ npm run test

> colorjs.io@0.4.5 test
> npx htest ./tests

(node:39202) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/lloydk/test/color.js/node_modules/.bin/htest:3
import run from "./node-run.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.9.0
```

**Comment by LeaVerou** [comment]
I think you have a much older version of htest. Can you run `npm install` again?

**Comment by lloydk** [comment]
> I think you have a much older version of htest. Can you run `npm install` again?
> 

deleted my node_modules folder and ran npm install again. same problem

is the htest code in the htest or htest.dev package? my node_modules/htest folder looks like this:

```
~/test/color.js/node_modules/htest:[main]$ ls
b.js  hello.js  package.json
```

**Comment by LeaVerou** [comment]
@svgeesus just had the same problem, turns out that even though I had 0.0.8 of htest.dev locally, the version in package-lock.json was 0.0.6. It should be now fixed, so please just pull and try again. :)

**Comment by svgeesus** [comment]
Works for me too, now.
